### ISSUE TITLE
Contributing back to Z-Push

### ISSUE THREAD

**Issue by matidau** [grommunio/grommunio-sync#14]
Hi Team,

It's been pointed out that this is a fork of Z-Push. Not sure how close your project is to the current Z-Push project, but wondering if you felt like contributing back. Particularly around AS 16.0/.1 support. :)

https://github.com/Z-Hub/Z-Push/issues/15

Cheers,
Mat

**Comment by jengelh** [comment]
g-sync was based on Z-Push, but has progressed and diverged quite a lot. There were some major changes in the interfaces, and the backend abstraction layer was dropped as it is not relevant to our server. Most of the work to support AS 16 and 16.1 needs to be done in the individual backends so that correct data can be sent. That change was only implemented for Grommunio and there are no plans to extend the other backends.

**Comment by matidau** [comment]
Thanks for the response and no problems 😄
